export type {
  BaseSectionConfig,
  BenefitsSectionConfig,
  CtaSectionConfig,
  HighlightsSectionConfig,
  ProcessSectionConfig,
  ServiceActionConfig,
  ServiceActionVariant,
  ServiceHeroConfig,
  ServiceHighlightItem,
  ServicePageConfig,
  ServiceProcessItem,
  ServiceSectionConfig,
  ServiceSectionTone,
  ServiceSectionType,
  ServiceTimelineItem,
  TagsSectionConfig,
  TimelineSectionConfig,
} from "@features/services/interfaces";
